export const DSA_TOPIC_OPTIONS = [
  { label: "Array", value: "array" },
  { label: "String", value: "string" },
  { label: "Linked List", value: "linkedlist" },
  { label: "Doubly Linked List", value: "doublylinkedlist" },
  { label: "Stack", value: "stack" },
  { label: "Queue", value: "queue" },
  { label: "Heap", value: "heap" },
  { label: "Hash Table", value: "hashtable" },
  { label: "Math", value: "math" },
  { label: "Two Pointers", value: "twopointers" },
  { label: "Sliding Window", value: "slidingwindow" },
  { label: "BFS", value: "bfs" },
  { label: "DFS", value: "dfs" },
  { label: "Matrix", value: "matrix" },
  { label: "Bit Manipulation", value: "bitmanipulation" },
  { label: "Prefix Sum", value: "prefixsum" },
  { label: "Tree", value: "tree" },
  { label: "Binary Tree", value: "binarytree" },
  { label: "Binary Search Tree", value: "binarysearchtree" },
  { label: "Graph", value: "graph" },
  { label: "Union Find", value: "unionfind" },
  { label: "Number Theory", value: "numbertheory" },
  { label: "Ordered Set", value: "orderedset" },
  { label: "Segment Tree", value: "segmenttree" },
  { label: "Fenwick Tree (BIT)", value: "binaryindexedtree" },
  { label: "Trie", value: "trie" },
  { label: "Combinatorics", value: "combinatorics" },
  { label: "Bitmask", value: "bitmask" },
  { label: "Divide and Conquer", value: "divideandconquer" },
  { label: "Recursion", value: "recursion" },
  { label: "Backtracking", value: "backtracking" },
  { label: "Dynamic Programming", value: "dp" },
  { label: "Memoization", value: "memoization" },
  { label: "Greedy", value: "greedy" },
  { label: "Game Theory", value: "gametheory" },
  { label: "Geometry", value: "geometry" },
  { label: "Hash Function", value: "hashfunction" },
  { label: "String Matching", value: "stringmatching" },
  { label: "Topological Sort", value: "topologicalsort" },
  { label: "Rolling Hash", value: "rollinghash" },
  { label: "Monotonic Stack", value: "monotonicstack" },
  { label: "Monotonic Queue", value: "monotonicqueue" },
  { label: "Merge Sort", value: "mergesort" },
  { label: "Counting Sort", value: "countingsort" },
  { label: "Quickselect", value: "quickselect" },
  { label: "Suffix Array", value: "suffixarray" },
  { label: "Line Sweep", value: "linesweep" },
  { label: "Minimum Spanning Tree", value: "minimumspanningtree" },
  { label: "Bucket Sort", value: "bucketsort" },
  { label: "Radix Sort", value: "radixsort" },
  { label: "Rejection Sampling", value: "rejectionsampling" },
  { label: "Biconnected Component", value: "biconnectedcomponent" },
];

export const CP_TOPIC_OPTIONS = [
  { label: "Implementation", value: "implementation" },
  { label: "Math", value: "math" },
  { label: "Greedy", value: "greedy" },
  { label: "Dynamic Programming", value: "dp" },
  { label: "Data Structures", value: "data-structures" },
  { label: "Brute Force", value: "brute-force" },
  { label: "Constructive Algorithms", value: "constructive-algorithms" },
  { label: "Graphs", value: "graph" },
  { label: "Sorting", value: "sorting" },
  { label: "Binary Search", value: "searching" },
  { label: "DFS", value: "dfs" },
  { label: "Trees", value: "trees" },
  { label: "Strings", value: "string" },
  { label: "Number Theory", value: "numbertheory" },
  { label: "Combinatorics", value: "combinatorics" },
  { label: "Special", value: "special" },
  { label: "Geometry", value: "geometry" },
  { label: "Bitmasks", value: "bitmask" },
  { label: "Two Pointers", value: "twopointers" },
  { label: "Disjoint Set Union (DSU)", value: "unionfind" },
  { label: "Shortest Paths", value: "shortestpath" },
  { label: "Probabilities", value: "probabilities" },
  { label: "Divide and Conquer", value: "divideandconquer" },
  { label: "Hashing", value: "hashfunction" },
  { label: "Games", value: "gametheory" },
  { label: "Flows", value: "flow-matching" },
];

export const getTopicOptionsForMode = (mode) =>
  mode === "cp" ? CP_TOPIC_OPTIONS : DSA_TOPIC_OPTIONS;
